<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ytmusic-play-button-renderer_Top result_play-button</name>
   <tag></tag>
   <elementGuidId>1ca08246-1927-431c-bd5a-afa3e1e7d5c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ytmusic-play-button-renderer[@id='play-button'])[18]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ytmusic-responsive-list-item-renderer.style-scope.ytmusic-shelf-renderer > div.left-items.style-scope.ytmusic-responsive-list-item-renderer > ytmusic-item-thumbnail-overlay-renderer.thumbnail-overlay.style-scope.ytmusic-responsive-list-item-renderer > #content > #play-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ytmusic-play-button-renderer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>play-button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytmusic-item-thumbnail-overlay-renderer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>state</name>
      <type>Main</type>
      <value>default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Play Father and Son (live, Yusuf's Cafe) - Cat Stevens</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>MUSIC_PLAY_BUTTON_SIZE_SMALL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elevation</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-page&quot;)/ytmusic-tabbed-search-results-renderer[@class=&quot;style-scope ytmusic-search-page&quot;]/div[@class=&quot;content style-scope ytmusic-tabbed-search-results-renderer&quot;]/ytmusic-section-list-renderer[@class=&quot;style-scope ytmusic-tabbed-search-results-renderer&quot;]/div[@id=&quot;contents&quot;]/ytmusic-shelf-renderer[@class=&quot;style-scope ytmusic-section-list-renderer&quot;]/div[@id=&quot;contents&quot;]/ytmusic-responsive-list-item-renderer[@class=&quot;style-scope ytmusic-shelf-renderer&quot;]/div[@class=&quot;left-items style-scope ytmusic-responsive-list-item-renderer&quot;]/ytmusic-item-thumbnail-overlay-renderer[@class=&quot;thumbnail-overlay style-scope ytmusic-responsive-list-item-renderer&quot;]/div[@id=&quot;content&quot;]/ytmusic-play-button-renderer[@id=&quot;play-button&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//ytmusic-play-button-renderer[@id='play-button'])[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='content']/ytmusic-play-button-renderer)[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top result'])[1]/following::ytmusic-play-button-renderer[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albums'])[1]/following::ytmusic-play-button-renderer[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Father and Son (live, Yusuf', &quot;'&quot;, 's Cafe)')])[1]/preceding::ytmusic-play-button-renderer[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video'])[1]/preceding::ytmusic-play-button-renderer[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ytmusic-responsive-list-item-renderer/div/ytmusic-item-thumbnail-overlay-renderer/div/ytmusic-play-button-renderer</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ytmusic-play-button-renderer[@id = 'play-button']</value>
   </webElementXpaths>
</WebElementEntity>
